---
- name: Deploy Application into eks cluster 
  hosts: all  # Replace with your target Kubernetes master host or group
  gather_facts: false  # No need to gather facts for this playbook
  become: true
  tasks:
    - name: Copy k8s_deployment.yaml file to eks cluster
      copy:
        src: /var/lib/jenkins/workspace/cicd/Ansible/playbook.yaml  # Assuming Jenkins workspace variable
        dest: /home/ec2-user/

    - name: Apply Deployment
      ansible.builtin.command: kubectl apply -f /home/ec2-user/k8s_deployment.yaml
    
