---
- name: Deploy Application into EKS cluster
  hosts: localhost  # Replace with your target Kubernetes master host or group
  gather_facts: false  # No need to gather facts for this playbook
  become: true
  tasks:
    - name: Copy playbook.yaml file to eks cluster
      copy:
        src: /var/lib/jenkins/workspace/cicd-pipeline/Ansible  # Assuming Jenkins workspace variable
        dest: /etc/ansible/playbooks/playbook.yaml  # Including the filename

    - name: Apply Deployment
      ansible.builtin.command:
        cmd: kubectl apply -f /etc/ansible/playbooks/playbook.yaml
        chdir: /etc/ansible/playbooks  # Optional: set working directory
