---
- name: Deploy Application into eks cluster 
  hosts: all  # Replace with your target Kubernetes master host or group
  gather_facts: false  # No need to gather facts for this playbook
  become: true
  become_user: root
  tasks:
    - name: Copy playbook.yaml file to eks cluster
      copy:
        src: /var/lib/jenkins/workspace/cicd-project/Ansible/playbook.yaml  # Assuming Jenkins workspace variable
        dest: /etc/ansible/playbooks

    - name: Apply Deployment
      ansible.builtin.command: kubectl apply -f /etc/ansible/playbooks/playbook.yaml
    
